### PR TITLE
Files for ghgt14

### PR DESCRIPTION
**Pull request by totto82**
Since this is the first stuff we put into opm-publications I would like some discussion about 
1) copyright and license 
2) the level of comments and the readability. I did not spend much time time on writing comments and making the files nice. I just pushed what I had. 
3) If we really what the results to be easily reproducible for others also in the future we probably should provide a docker container or a script that downloads, builds and run the simulations. For this small paper I think this will be too much work will little gain.

### CODE REVIEW

**Comment by totto82** [comment]
@atgeirr @abir Any comments on this?

**Comment by alfbr** [comment]
AFAIK, the solvent option used was merged to master, so from a source code perspective I believe it is sufficient to point to the first release of OPM after the simulation studies were done. However, the changes done to the data set needs to be shared. Actually, the license demands it.

**Comment by atgeirr** [comment]
Are the scripts here, and the files in https://github.com/rolfjl/Norne-Initial-Ensemble taken together enough to reproduce the data files used for the experiment?

**Comment by alfbr** [comment]
This PR contains all changes needed to the Norne data set, in addition to the scripts used for creating ensembles. Basically everything that is needed to reproduce the published results. Hence, merging. Thank you!

**Pull request merged**
